---
title: "Access to public accounts"
author: "MariaProkofieva"
date: "24/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("devtools")
#library(devtools)

#https://github.com/bergant/xbrlus
#devtools::install_github("bergant/xbrlus") 

#https://github.com/bergant/finstr
#devtools::install_github("bergant/finstr") 

#---------------------
#SETTINGS
#XBRL https://xbrl.us/home/about/legal/xbrl-api-clientid/
#client=RBusiness
#Client ID: d47a6cf4-005e-44bd-a8c5-fe61bfe43844
#Client Secret: 094679e1-b0c7-41bf-aee7-6ee36edbed46

XBRLUS_API_KEY=EnterKeyHere

library(XBRL)
library(xbrlus)
library(finstr)
library(tidyverse)
```

#Financial statements and accounting data

Working with accounting starts with getting access to accounting data.

While some paid access is available for accounting data, we are interested in working with free resources at this stage and the blessing comes from a requirement for `public` companies to have their data freely available, though in a "messy" form.

Common issues here:

- data is available as annual reports in various formats, such as pdf, docx, etc

- data comes in various structures - in most cases the format for accounting statements are not fixed to allow companies to communicate `true and fair` presentation of accounts

- country-specific data repositories, e.g. `EDGAR` in US and `Company House` in UK

- country-specific requirements for preparation of accounts, e.g. `IFRS` (International Financial Reporting Standards) and `US GAAP` (General Accepted Accounting Principles).

We are going to work with US accounting data at this stage and [EDGAR](https://www.sec.gov/edgar.shtml)

`EDGAR` uses `XBRL` which is a structured format to present information. This "structered data" is available via [`XBRL API`](https://xbrl.us/home/use/xbrl-api/)

Quick reminder: `API` is `Application Program Interface`. It includes a set of `endpoints` that are used to access the data. This allows to have structure in the data and stardardise access. It allows accessing data easier since there is one interface and just different endpoints to use. 


[`XBRL.US`](https://xbrl.us) provides access to:

- XBRL US Database of Public Filings (including facts, report and taxonomy details) and - Data Quality Committee (DQC) error messages for all SEC-submitted filings.

### 1. Setting up xbrl access

To start you need to create your xbrl account [here](https://xbrl.us/wp-login.php?action=register)


### 2. Collecting the data

To collect the data you need to know the company's ID and what type of data you want

With the company's ID, it should looke like this 

With the type of data, big help is to look at the XBRL taxonomy [here](https://xbrl.us/xbrl-taxonomy/2019-us-gaap/)

The `CIK` is the unique numerical identifier assigned by the EDGAR system to filers when they sign up to make filings to the SEC. CIK numbers remain unique to the filer; they are not recycled.


